delete from s_functions;INSERT INTO s_functions VALUES ('01.00.00.00.00.00', 'USER', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('01.10.00.00.00.00', '{L-ENGProfile-L}{L-INAProfil-L}', 'userlist.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('01.10.01.00.00.00', 'Create', NULL, NULL, 'USER_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('01.10.02.00.00.00', 'Edit', NULL, NULL, 'USER_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('01.10.03.00.00.00', 'Delete', NULL, NULL, 'USER_DELETE', NULL, NULL);
INSERT INTO s_functions VALUES ('01.10.04.00.00.00', 'Set Password', NULL, NULL, 'USER_PASSWORD', NULL, NULL);
INSERT INTO s_functions VALUES ('01.15.00.00.00.00', 'Role', 'role_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('01.20.00.00.00.00', 'Sessions', 'LIST_SESSIONS', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('02.00.00.00.00.00', '{L-ENGCAPACITY-L}{L-INAKAPASITAS-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('02.10.00.00.00.00', '{L-ENGApproval Limits-L}{L-INALimit Persetujuan-L}', 'capacity_edit.approval.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('02.10.01.00.00.00', 'Edit Limit TSI', NULL, NULL, 'CAPA_APPROVAL_TSI_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('02.10.02.00.00.00', 'Edit Limit KIaim', NULL, NULL, 'CAPA_APPROVAL_CLAIM_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('02.10.03.00.00.00', 'Approve Flag 1', NULL, NULL, 'CAPA_TSI_APPROVE1', NULL, NULL);
INSERT INTO s_functions VALUES ('02.10.04.00.00.00', 'Approve Flag 2', NULL, NULL, 'CAPA_TSI_APPROVE2', NULL, NULL);
INSERT INTO s_functions VALUES ('02.10.05.00.00.00', 'Approve Flag 3', NULL, NULL, 'CAPA_TSI_APPROVE3', NULL, NULL);
INSERT INTO s_functions VALUES ('02.10.06.00.00.00', 'Approve Flag 4', NULL, NULL, 'CAPA_TSI_APPROVE4', NULL, NULL);
INSERT INTO s_functions VALUES ('02.20.00.00.00.00', '{L-ENGComission Limits-L}{L-INALimit Komisi-L}', 'capacity_edit.commission.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('02.20.01.00.00.00', 'Edit', NULL, NULL, 'CAPA_COMM_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('02.20.02.00.00.00', 'Create', NULL, NULL, 'CAPA_COMM_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('02.20.03.00.00.00', 'Approve Flag 1', NULL, NULL, 'CAPA_COMM_APPROVE1', NULL, NULL);
INSERT INTO s_functions VALUES ('02.20.04.00.00.00', 'Approve Flag 2', NULL, NULL, 'CAPA_COMM_APPROVE2', NULL, NULL);
INSERT INTO s_functions VALUES ('02.20.05.00.00.00', 'Approve Flag 3', NULL, NULL, 'CAPA_COMM_APPROVE3', NULL, NULL);
INSERT INTO s_functions VALUES ('02.20.06.00.00.00', 'Approve Flag 4', NULL, NULL, 'CAPA_COMM_APPROVE4', NULL, NULL);
INSERT INTO s_functions VALUES ('02.30.00.00.00.00', '{L-ENGComission Limit Company Group-L}{L-INALimit Komisi Group Perusahaan-L}', 'capacity_edit.commissiongroup.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('02.30.01.00.00.00', 'Edit', NULL, NULL, 'CAPA_COMM_GROUP_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('02.40.00.00.00.00', '{L-ENGComission Setting-L}{L-INAPembagian Komisi-L}', 'capacity_edit.commissionsetting.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('10.00.00.00.00.00', 'Customer Management', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('10.10.00.00.00.00', '{L-ENGCustomer Management-L}{L-INAData Customer-L}', 'entity_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('10.10.10.00.00.00', 'Navigate Branch', NULL, NULL, 'ENT_MASTER_NAV_BR', NULL, NULL);
INSERT INTO s_functions VALUES ('10.10.20.00.00.00', 'Jenis Perusahaan Lain', NULL, NULL, 'SELECT_COMP_TYPE', NULL, NULL);
INSERT INTO s_functions VALUES ('10.11.00.00.00.00', '{L-ENGCompany Group-L}{L-INAGrup Perusahaan-L}', 'company_group_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('14.00.00.00.00.00', 'Working Timeline', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('14.10.00.00.00.00', '{L-ENGWorking Timeline-L}{L-INAWorking Timeline-L}', 'register_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('14.10.01.00.00.00', 'Navigate Branch', NULL, NULL, 'REGISTER_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('15.00.00.00.00.00', 'Marketing', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('15.10.00.00.00.00', '{L-ENGQuotation-L}{L-INAPenawaran-L}', 'policy_list.proposal.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('15.10.01.00.00.00', 'Navigate Branch', NULL, NULL, 'POL_PROP_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('15.10.02.00.00.00', 'Edit', NULL, NULL, 'POL_PROP_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('15.10.03.00.00.00', 'Create', NULL, NULL, 'POL_PROP_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('15.10.04.00.00.00', 'Approval', NULL, NULL, 'POL_PROP_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('15.10.05.00.00.00', 'Print', NULL, NULL, 'POL_PROP_PRINT', NULL, NULL);
INSERT INTO s_functions VALUES ('15.10.06.00.00.00', 'Navigate Region', NULL, NULL, 'POL_PROP_NAVREG', NULL, NULL);
INSERT INTO s_functions VALUES ('15.11.00.00.00.00', '{L-ENGParent Policy-L}{L-INAPolis Induk-L}', 'policy_parent_list.parent.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('15.12.00.00.00.00', '{L-ENGPerjanjian Kerjasama-L}{L-INAPerjanjian Kerjasama-L}', 'pks_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('15.20.00.00.00.00', '{L-ENGReport-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('15.20.01.00.00.00', '{L-ENGProduction Report-L}{L-INALaporan Produksi-L}', NULL, '/prod_marketing_report.go.crux?rpt=marketing', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('15.21.00.00.00.00', '{L-ENGReport-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('15.21.01.00.00.00', '{L-ENGProduction Report of PKS-L}{L-INALaporan Produksi PKS-L}', NULL, '/prod_pks.go.crux?rpt=pks', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.00.00.00.00.00', 'Underwriting', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.00.00.00.00', 'Underwriting', 'policy_list.underwrit.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.01.00.00.00', 'Navigate Branch', NULL, NULL, 'POL_UWRIT_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.02.00.00.00', 'Edit', NULL, NULL, 'POL_UWRIT_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.03.00.00.00', 'Create', NULL, NULL, 'POL_UWRIT_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.04.00.00.00', 'Approval', NULL, NULL, 'POL_UWRIT_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.05.00.00.00', 'Print', NULL, NULL, 'POL_UWRIT_PRINT', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.06.00.00.00', 'Create Policy History', NULL, NULL, 'POL_UWRIT_CREATE_HISTORY', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.07.00.00.00', 'Approve U/W', NULL, NULL, 'POL_UWRIT_APR_UW', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.08.00.00.00', 'Input Payment Date', NULL, NULL, 'POL_UWRIT_PAYMENT_DATE', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.09.00.00.00', 'Bonding Division', NULL, NULL, 'BONDING_DIVISION', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.10.00.00.00', 'Reverse Data', NULL, NULL, 'CAN_REVERSE', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.11.00.00.00', 'Input No Polis Manual', NULL, NULL, 'CAN_INPUT_MANUAL_POL', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.12.00.00.00', 'Input Polis Sementara', NULL, NULL, 'CAN_INPUT_TEMP_POL', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.13.00.00.00', 'Setujui Oleh Direksi', NULL, NULL, 'APPROVE_BY_DIRECTOR', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.14.00.00.00', 'Swap Premi Koas > Premi ABA', NULL, NULL, 'SWAP_COAS_PREMIUM', NULL, NULL);
INSERT INTO s_functions VALUES ('20.10.15.00.00.00', 'Navigate Region', NULL, NULL, 'POL_UWRIT_NAVREG', NULL, NULL);
INSERT INTO s_functions VALUES ('20.20.00.00.00.00', 'Risk Assessment', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.20.10.00.00.00', 'Assessment', NULL, '/pages/riskassessment/assessment.htm', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.30.00.00.00.00', 'Setup', 'CONFIGURE&GROUP=UWRIT', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.40.00.00.00.00', 'Treaty', 'treaty_list.list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.50.00.00.00.00', 'Block Risk', 'zone_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.60.00.00.00.00', 'Print Kwitansi', 'policy_rcp.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.70.00.00.00.00', 'Risk Category', 'risk_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.71.00.00.00.00', '{L-ENGClausules-L}{L-INAKlausula-L}', 'clausules_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.90.00.00.00.00', 'Surat Pengantar', 'policy_ltr.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.91.00.00.00.00', '{L-ENGReport-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.91.01.00.00.00', '{L-ENGProduction Report-L}{L-INALaporan Produksi-L}', NULL, '/prod_marketing_report.go.crux?rpt=marketing', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.80.00.00.00.00', 'Cover Note', 'cover_note_list.titipan.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('20.80.01.00.00.00', 'Navigate Branch', NULL, NULL, 'POL_COVERNOTE_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('20.80.02.00.00.00', 'Edit', NULL, NULL, 'POL_COVERNOTE_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('20.80.03.00.00.00', 'Create', NULL, NULL, 'POL_COVERNOTE_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('20.80.04.00.00.00', 'Approval', NULL, NULL, 'POL_COVERNOTE_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('20.80.05.00.00.00', 'Print', NULL, NULL, 'POL_COVERNOTE_PRINT', NULL, NULL);
INSERT INTO s_functions VALUES ('20.92.00.00.00.00', 'Upload File', 'policy_upload.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.00.00.00.00.00', '{L-ENGReinsurance-L}{L-INAReasuransi-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.10.00.00.00.00', '{L-ENGReinsurance-L}{L-INAReasuransi-L} / Outward', 'policy_list.reas.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.10.01.00.00.00', 'Navigate Branch', NULL, NULL, 'POL_RI_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('25.10.02.00.00.00', 'Edit', NULL, NULL, 'POL_RI_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('25.10.03.00.00.00', 'Create', NULL, NULL, 'POL_RI_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('25.10.04.00.00.00', 'Approval', NULL, NULL, 'POL_RI_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('25.10.05.00.00.00', 'Print', NULL, NULL, 'POL_RI_PRINT', NULL, NULL);
INSERT INTO s_functions VALUES ('25.10.06.00.00.00', 'Manual Treaty', NULL, NULL, 'MANUAL_TREATY', NULL, NULL);
INSERT INTO s_functions VALUES ('25.10.07.00.00.00', 'Navigate Region', NULL, NULL, 'POL_RI_NAVREG', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.00.00.00.00', 'Inward', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.30.00.00.00.00', '{L-ENGReport-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.30.01.00.00.00', '{L-ENGProduction Report-L}{L-INALaporan Produksi-L}', NULL, '/prod_reinsurance_report.go.crux?rpt=reinsurance', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.31.00.00.00.00', '{L-ENGInward Report-L}{L-INALaporan Inward-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.31.01.00.00.00', '{L-ENGProduction Report-L}{L-INALaporan Produksi-L}', NULL, '/prod_inward.go.crux?rpt=inward', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.00.00.00.00.00', '{L-ENGClaim-L}{L-INAKlaim-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.10.00.00.00.00', '{L-ENGClaim-L}{L-INAKlaim-L}', 'policy_list.claim.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.10.01.00.00.00', 'Navigate Branch', NULL, NULL, 'POL_CLAIM_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('30.10.02.00.00.00', 'Edit', NULL, NULL, 'POL_CLAIM_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('30.10.03.00.00.00', 'Create', NULL, NULL, 'POL_CLAIM_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('30.10.04.00.00.00', 'Approval', NULL, NULL, 'POL_CLAIM_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('30.10.05.00.00.00', 'Print', NULL, NULL, 'POL_CLAIM_PRINT', NULL, NULL);
INSERT INTO s_functions VALUES ('30.10.08.00.00.00', 'Navigate Region', NULL, NULL, 'POL_CLAIM_NAVREG', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.00.00.00.00', '{L-ENGInward-L}{L-INAInward-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.30.00.00.00.00', '{L-ENGReport-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.30.01.00.00.00', '{L-ENGProduction Report-L}{L-INALaporan Produksi-L}', NULL, '/prod_claim_report.go.crux?rpt=claim', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.30.02.00.00.00', 'Pengajuan Klaim', 'policy_clm.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.31.00.00.00.00', '{L-ENGInward Report-L}{L-INALaporan Inward-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.31.01.00.00.00', '{L-ENGProduction Report-L}{L-INALaporan Produksi-L}', NULL, '/prod_inward.go.crux?rpt=inwardclm', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.40.00.00.00.00', 'Setup', 'CONFIGURE&GROUP=CLAIM', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.10.06.00.00.00', 'Edit No Surat Dll', NULL, NULL, 'POL_CLAIM_EDIT2', NULL, NULL);
INSERT INTO s_functions VALUES ('30.10.07.00.00.00', 'Setujui Oleh Direksi', NULL, NULL, 'CLAIM_APPROVE_BY_DIRECTOR', NULL, NULL);
INSERT INTO s_functions VALUES ('33.00.00.00.00.00', 'Data Searching', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('33.10.00.00.00.00', 'PA Kreasi', 'policy_form.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('33.10.01.00.00.00', 'Navigate Branch', NULL, NULL, 'KREASI_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('33.20.00.00.00.00', 'Kendaraan Bermotor', 'vehicle_search.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('33.30.00.00.00.00', 'Flexible Search', 'policy_search.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.00.00.00.00.00', '{L-ENGFinance-L}{L-INAKeuangan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.00.05.10.00.00', 'Create', NULL, NULL, 'SETTLR_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.00.05.20.00.00', 'Edit', NULL, NULL, 'SETTLR_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.00.05.30.00.00', 'Approve', NULL, NULL, 'SETTLR_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('35.00.05.40.00.00', 'Navigate Branch', NULL, NULL, 'SETTLR_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('35.00.05.50.00.00', 'Void', NULL, NULL, 'SETTLR_VOID', NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.00.00.00.00', 'Pembayaran', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.06.00.00.00.00', '{L-ENGPayment Monitoring-L}{L-INAMonitoring Pembayaran-L}', 'policy_data.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.00.00.00.00', 'Deposito', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.10.00.00.00', 'Pembentukan Deposito', 'pembentukan_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.10.10.00.00', 'Navigate Branch', NULL, NULL, 'DEPO_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.10.20.00.00', 'Approval', NULL, NULL, 'DEPO_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.20.00.00.00', 'Pencairan Deposito', 'pencairan_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.20.10.00.00', 'Navigate Branch', NULL, NULL, 'CAIR_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.20.20.00.00', 'Approval', NULL, NULL, 'CAIR_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.30.00.00.00', 'Bunga Deposito', 'bunga_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.30.10.00.00', 'Navigate Branch', NULL, NULL, 'BUNGA_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.30.20.00.00', 'Approval', NULL, NULL, 'BUNGA_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.40.00.00.00', 'Perpanjangan Deposito', 'perpanjangan_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.40.10.00.00', 'Navigate Branch', NULL, NULL, 'RENEWAL_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('35.07.40.20.00.00', 'Approval', NULL, NULL, 'RENEWAL_APRV', NULL, NULL);
INSERT INTO s_functions VALUES ('35.08.00.00.00.00', '{L-ENGReport-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.08.10.00.00.00', '{L-ENGDeposito Report-L}{L-INALaporan Deposito-L}', NULL, '/prod_deposito.go.crux?rpt=deposito', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.00.00.00.00', '{L-ENGTransaction-L}{L-INATransaksi-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.26.00.00.00.00', 'Surat Hutang', 'surathutanglist.crux&trx=50', '/main.ctl?EVENT=surathutanglist.crux&trx=50', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.27.00.00.00.00', '{L-ENGTitipan Premi-L}{L-INATitipan Premi-L}', 'titipan_premi_list.crux&glid=6', '/main.ctl?EVENT=titipan_premi_list.crux&glid=6', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.99.00.00.00', 'Navigate Branch', NULL, NULL, 'ARINVOICE_NAVBR', NULL, NULL);
INSERT INTO s_functions VALUES ('35.25.00.00.00.00', 'Setup', 'CONFIGURE&GROUP=AR_AP', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.30.00.00.00.00', '{L-ENGReporting-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('36.30.00.00.00.00', '{L-ENGReport-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('36.30.01.00.00.00', '{L-ENGFinance Report-L}{L-INALaporan Keuangan-L}', NULL, '/prod_finance_report.go.crux?rpt=finance', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.30.44.00.00.00', '{L-ENGAR/AP Detail-L}{L-INADetil Hutang Piutang-L}', 'rptArAPDetail.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.30.45.00.00.00', '{L-ENGR/I Payable Summary-L}{L-INARekapitulasi Hutang Reasuransi-L}', 'arreport.crux&mode=AP', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.30.50.00.00.00', '{L-ENGR/I Receivable Summary-L}{L-INARekapitulasi Piutang Reasuransi-L}', 'arreport.crux&mode=AR', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.30.55.00.00.00', '{L-ENGTechnical Account Statement-L}{L-INATechnical Account Statement-L}', 'rptSOAReinsurance.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.00.00.00.00.00', '{L-ENGAccounting-L}{L-INAAkuntansi-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.10.00.00.00.00', '{L-ENGJournal Entry-L}{L-INAJurnal Entry-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.10.10.00.00.00', '{L-ENGGeneral Journal-L}{L-INAJurnal Umum-L}', 'gl_list.crux&glid=1', '/main.ctl?EVENT=gl_list.crux&glid=1', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.10.15.00.00.00', '{L-ENGBank Cash Journal-L}{L-INAJurnal Kas Bank-L}', 'cashbankGL_list.crux&glid=2', '/main.ctl?EVENT=gl_list.crux&glid=2', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.10.20.00.00.00', '{L-ENGClaim Advanced Payment-L}{L-INAUang Muka Klaim-L}', 'free_gl_list.crux&glid=3', '/main.ctl?EVENT=free_gl_list.crux&glid=3', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.10.21.00.00.00', '{L-ENGPremium Advanced Payment-L}{L-INAUang Muka Premi-L}', 'premi_gl_list.crux&glid=4', '/main.ctl?EVENT=premi_gl_list.crux&glid=4', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.10.22.00.00.00', '{L-ENGCommission Payment-L}{L-INAUang Muka Komisi-L}', 'comission_gl_list.crux&glid=5', '/main.ctl?EVENT=comission_gl_list.crux&glid=5', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.10.23.00.00.00', '{L-ENGBusiness Development Journal-L}{L-INAJurnal Pembinaan Bisnis-L}', 'pb_gl_list.crux&glid=6', '/main.ctl?EVENT=pb_gl_list.crux&glid=6', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.10.24.00.00.00', '{L-ENGSyariah Journal-L}{L-INAJurnal Syariah-L}', 'syariah_gl_list.crux&glid=7', '/main.ctl?EVENT=syariah_gl_list.crux&glid=7', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.10.25.00.00.00', 'Evaluasi Pelaksanaan RKAP', 'evaluate_list.crux&glid=8', '/main.ctl?EVENT=evaluate_list.crux&glid=8', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.17.00.00.00.00', '{L-ENGReport-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.17.01.00.00.00', '{L-ENGAccounting Report-L}{L-INALaporan Akuntansi-L}', NULL, '/prod_account.go.crux?rpt=accounting', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.16.00.00.00.00', '{L-ENGReport-L}{L-INALaporan-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.00.00.00.00', 'Setup', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.10.00.00.00', 'Account Type', 'GL_ACCT_TYPE', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.15.00.00.00', 'Account Mask', 'CONFIGURE&GROUP=GL_ACCT_MASK', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.20.00.00.00', 'Fiscal Year', 'CONFIGURE&GROUP=GL_FISCAL_YR', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.25.00.00.00', 'Journal Master', 'GL_J_MASTER', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.30.00.00.00', 'Cost Center', 'GL_DEPT_LIST', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.35.00.00.00', 'Periods', 'GL_PERIODS', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.40.00.00.00', 'Accounts', 'account_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.45.00.00.00', 'Currency', 'currency_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.45.10', 'Setup', 'CONFIGURE&GROUP=GL_CCY', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.20.45.15', 'Exchange Rate', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.00.00.00.00.00', 'Utilities', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.10.00.00.00.00', 'Schedule of Policy', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.15.00.00.00.00', '{L-ENGInsurance Tools-L}{L-INAInsurance Tools-L}', 'printpolicywording.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.20.00.00.00.00', '{L-ENGNews Ticker-L}{L-INANews Ticker-L}', 'CONFIGURE&GROUP=NEWS', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.21.00.00.00.00', '{L-ENGAnnouncement-L}{L-INAPengumuman-L}', 'announcement.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.25.00.00.00.00', 'Data Export', NULL, '/prod_utilities_report.go.crux?rpt=utilities', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.30.00.00.00.00', '{L-ENGGuidance-L}{L-INAPanduan-L}', 'utilities.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.35.00.00.00.00', 'Transfer Data', NULL, '/prod_utilities_report.go.crux?rpt=transfer', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.40.00.00.00.00', 'Fix Data', 'fix_data.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('45.45.00.00.00.00', '{L-ENGArchive-L}{L-INAArsip-L}', 'archivelist.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('50.00.00.00.00.00', 'Maintenance', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('50.01.00.00.00.00', 'Documents', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('50.01.01.00.00.00', 'Super Edit', NULL, NULL, 'POL_SUPER_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('95.00.00.00.00.00', 'SYSTEM SETTINGS', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('95.01.00.00.00.00', 'Logging', 'CONFIGURE&GROUP=LOG', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('95.02.00.00.00.00', 'System', 'CONFIGURE&GROUP=SYS', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('95.03.00.00.00.00', 'General', 'CONFIGURE&GROUP=GENERAL', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('95.05.00.00.00.00', 'System Monitor', 'sysmon.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('95.06.00.00.00.00', 'SQI', 'sqi.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('95.30.00.00.00.00', 'Clear Pool', 'CLR_POOL', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('96.00.00.00.00.00', 'TASK SCHEDULER', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('96.01.00.00.00.00', 'Config', 'CONFIG_JOB', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('96.02.00.00.00.00', 'Log', 'JOB_LOG_VIEW', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('97.00.00.00.00.00', 'Address Management', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('97.20.00.00.00.00', '{L-ENGContacts-L}{L-INAKontak Alamat-L}', 'contact_list.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('98.00.00.00.00.00', '{L-ENGMail-L}{L-INASurat-L}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('98.10.00.00.00.00', '{L-ENGInbox-L}{L-INASurat Masuk-L}', 'incominglist.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('98.10.01.00.00.00', 'Create', NULL, NULL, 'INCOMING_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('98.10.02.00.00.00', 'Edit', NULL, NULL, 'INCOMING_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('98.10.03.00.00.00', 'Delete', NULL, NULL, 'INCOMING_DELETE', NULL, NULL);
INSERT INTO s_functions VALUES ('98.20.00.00.00.00', '{L-ENGOutbox-L}{L-INASurat Keluar-L}', 'outcominglist.crux', NULL, NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('98.20.01.00.00.00', 'Create', NULL, NULL, 'OUTCOMING_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('98.20.02.00.00.00', 'Edit', NULL, NULL, 'OUTCOMING_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('98.20.03.00.00.00', 'Delete', NULL, NULL, 'OUTCOMING_DELETE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.25.00', 'Beginning Balance', 'invoicelist.crux&trx=4', '/main.ctl?EVENT=invoicelist.crux&trx=4', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.25.01', 'Create', NULL, NULL, 'AR_TRX_4_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.25.02', 'Edit', NULL, NULL, 'AR_TRX_4_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.25.03', 'View', NULL, NULL, 'AR_TRX_4_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.25.04', 'Approve', NULL, NULL, 'AR_TRX_4_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.30.00', 'Premi - Direct', 'invoicelist.crux&trx=5', '/main.ctl?EVENT=invoicelist.crux&trx=5', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.30.01', 'Create', NULL, NULL, 'AR_TRX_5_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.30.02', 'Edit', NULL, NULL, 'AR_TRX_5_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.30.03', 'View', NULL, NULL, 'AR_TRX_5_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.30.04', 'Approve', NULL, NULL, 'AR_TRX_5_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.36.00', 'Komisi', 'invoicelist.crux&trx=11', '/main.ctl?EVENT=invoicelist.crux&trx=11', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.36.01', 'Create', NULL, NULL, 'AR_TRX_11_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.36.02', 'Edit', NULL, NULL, 'AR_TRX_11_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.36.03', 'View', NULL, NULL, 'AR_TRX_11_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.36.04', 'Approve', NULL, NULL, 'AR_TRX_11_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.42.00', 'R/I Claim Receivable', 'invoicelist.crux&trx=14', '/main.ctl?EVENT=invoicelist.crux&trx=14', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.42.01', 'Create', NULL, NULL, 'AR_TRX_14_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.42.02', 'Edit', NULL, NULL, 'AR_TRX_14_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.42.03', 'View', NULL, NULL, 'AR_TRX_14_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.42.04', 'Approve', NULL, NULL, 'AR_TRX_14_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.43.00', 'AR/AP Titipan', 'invoicelist.crux&trx=15', '/main.ctl?EVENT=invoicelist.crux&trx=15', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.43.01', 'Create', NULL, NULL, 'AR_TRX_15_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.43.02', 'Edit', NULL, NULL, 'AR_TRX_15_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.43.03', 'View', NULL, NULL, 'AR_TRX_15_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.43.04', 'Approve', NULL, NULL, 'AR_TRX_15_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.41.00', 'R/I Premium Payable', 'invoicelist.crux&trx=13', '/main.ctl?EVENT=invoicelist.crux&trx=13', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.41.01', 'Create', NULL, NULL, 'AR_TRX_13_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.41.02', 'Edit', NULL, NULL, 'AR_TRX_13_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.41.03', 'View', NULL, NULL, 'AR_TRX_13_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.41.04', 'Approve', NULL, NULL, 'AR_TRX_13_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.35.00', 'Premi Payable - Coas Out', 'invoicelist.crux&trx=10', '/main.ctl?EVENT=invoicelist.crux&trx=10', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.35.01', 'Create', NULL, NULL, 'AR_TRX_10_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.35.02', 'Edit', NULL, NULL, 'AR_TRX_10_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.35.03', 'View', NULL, NULL, 'AR_TRX_10_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.35.04', 'Approve', NULL, NULL, 'AR_TRX_10_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.32.00', 'Premi - Coas In', 'invoicelist.crux&trx=7', '/main.ctl?EVENT=invoicelist.crux&trx=7', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.32.01', 'Create', NULL, NULL, 'AR_TRX_7_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.32.02', 'Edit', NULL, NULL, 'AR_TRX_7_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.32.03', 'View', NULL, NULL, 'AR_TRX_7_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.32.04', 'Approve', NULL, NULL, 'AR_TRX_7_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.31.00', 'Premi - Coas Out', 'invoicelist.crux&trx=6', '/main.ctl?EVENT=invoicelist.crux&trx=6', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.31.01', 'Create', NULL, NULL, 'AR_TRX_6_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.31.02', 'Edit', NULL, NULL, 'AR_TRX_6_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.31.03', 'View', NULL, NULL, 'AR_TRX_6_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.31.04', 'Approve', NULL, NULL, 'AR_TRX_6_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.40.00', 'Claim Payable', 'invoicelist.crux&trx=12', '/main.ctl?EVENT=invoicelist.crux&trx=12', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.40.01', 'Create', NULL, NULL, 'AR_TRX_12_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.40.02', 'Edit', NULL, NULL, 'AR_TRX_12_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.40.03', 'View', NULL, NULL, 'AR_TRX_12_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.40.04', 'Approve', NULL, NULL, 'AR_TRX_12_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.02.00', 'Inward Treaty', 'invoiceinwardtreatylist.crux&trx=2', '/main.ctl?EVENT=invoiceinwardtreatylist.crux&trx=2', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.02.01', 'Create', NULL, NULL, 'AR_TRX_2_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.02.02', 'Edit', NULL, NULL, 'AR_TRX_2_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.02.03', 'View', NULL, NULL, 'AR_TRX_2_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.02.04', 'Approve', NULL, NULL, 'AR_TRX_2_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.01.00', 'Inward Facultative', 'invoicelist.crux&trx=1', '/main.ctl?EVENT=invoicelist.crux&trx=1', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.01.01', 'Create', NULL, NULL, 'AR_TRX_1_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.01.02', 'Edit', NULL, NULL, 'AR_TRX_1_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.01.03', 'View', NULL, NULL, 'AR_TRX_1_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.01.04', 'Approve', NULL, NULL, 'AR_TRX_1_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.02.00', 'Claim Inward Treaty', 'invoiceclaiminwardtreatylist.crux&trx=18', '/main.ctl?EVENT=invoiceclaiminwardtreatylist.crux&trx=18', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.02.01', 'Create', NULL, NULL, 'AR_TRX_18_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.02.02', 'Edit', NULL, NULL, 'AR_TRX_18_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.02.03', 'View', NULL, NULL, 'AR_TRX_18_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.02.04', 'Approve', NULL, NULL, 'AR_TRX_18_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.02.05', 'Create DLA', NULL, NULL, 'AR_TRX_18_CREATE_DLA', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.03.00', 'Inward Excess of Loss', 'invoicelist.crux&trx=3', '/main.ctl?EVENT=invoicelist.crux&trx=3', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.03.01', 'Create', NULL, NULL, 'AR_TRX_3_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.03.02', 'Edit', NULL, NULL, 'AR_TRX_3_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.03.03', 'View', NULL, NULL, 'AR_TRX_3_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.03.04', 'Approve', NULL, NULL, 'AR_TRX_3_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.01.00', 'Claim Inward Facultative', 'invoicelist.crux&trx=17', '/main.ctl?EVENT=invoicelist.crux&trx=17', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.01.01', 'Create', NULL, NULL, 'AR_TRX_17_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.01.02', 'Edit', NULL, NULL, 'AR_TRX_17_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.01.03', 'View', NULL, NULL, 'AR_TRX_17_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.01.04', 'Approve', NULL, NULL, 'AR_TRX_17_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.01.05', 'Create DLA', NULL, NULL, 'AR_TRX_17_CREATE_DLA', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.03.00', 'Claim Inward Excess of Loss', 'invoicelist.crux&trx=19', '/main.ctl?EVENT=invoicelist.crux&trx=19', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.03.01', 'Create', NULL, NULL, 'AR_TRX_19_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.03.02', 'Edit', NULL, NULL, 'AR_TRX_19_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.03.03', 'View', NULL, NULL, 'AR_TRX_19_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.03.04', 'Approve', NULL, NULL, 'AR_TRX_19_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('30.20.03.05', 'Create DLA', NULL, NULL, 'AR_TRX_19_CREATE_DLA', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.04.00', 'Profit Commision Inward Treaty', 'invoicelist.crux&trx=20', '/main.ctl?EVENT=invoicelist.crux&trx=20', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.04.01', 'Create', NULL, NULL, 'AR_TRX_20_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.04.02', 'Edit', NULL, NULL, 'AR_TRX_20_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.04.03', 'View', NULL, NULL, 'AR_TRX_20_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.04.04', 'Approve', NULL, NULL, 'AR_TRX_20_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.44.00', 'Claim Receivable - Coas Out', 'invoicelist.crux&trx=16', '/main.ctl?EVENT=invoicelist.crux&trx=16', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.44.01', 'Create', NULL, NULL, 'AR_TRX_16_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.44.02', 'Edit', NULL, NULL, 'AR_TRX_16_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.44.03', 'View', NULL, NULL, 'AR_TRX_16_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('35.20.44.04', 'Approve', NULL, NULL, 'AR_TRX_16_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.05.00', 'Profit Commision Outward Treaty', 'invoicelist.crux&trx=21', '/main.ctl?EVENT=invoicelist.crux&trx=21', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.05.01', 'Create', NULL, NULL, 'AR_TRX_21_CREATE', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.05.02', 'Edit', NULL, NULL, 'AR_TRX_21_EDIT', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.05.03', 'View', NULL, NULL, 'AR_TRX_21_VIEW', NULL, NULL);
INSERT INTO s_functions VALUES ('25.20.05.04', 'Approve', NULL, NULL, 'AR_TRX_21_APPROVE', NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.01.00.00', 'Penerimaan Premi', NULL, '/receiptlist.crux?arsid=1', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.02.00.00', 'Pembayaran Komisi', NULL, '/receiptpembayarankomisilist.crux?arsid=2', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.03.00.00', 'Pembayaran Uang Muka Komisi', NULL, '/receiptlist.crux?arsid=3', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.04.00.00', 'Pembayaran Uang Muka Premi', NULL, '/receiptlist.crux?arsid=5', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.05.00.00', 'AR Offset', NULL, '/receiptlist.crux?arsid=6', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.06.00.00', 'AP Offset', NULL, '/receiptlist.crux?arsid=7', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.07.00.00', 'Pembayaran Pajak', NULL, '/receiptpembayaranpajaklist.crux?arsid=8', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.08.00.00', 'Pembayaran Reasuransi', NULL, '/receiptpembayaranreaslist.crux?arsid=9', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.09.00.00', 'Pembayaran Klaim', NULL, '/receiptlist.crux?arsid=10', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.10.00.00', 'Penerimaan Klaim Reasuransi', NULL, '/receiptlist3.crux?arsid=11', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.11.00.00', 'Pembayaran Ko-Asuransi', NULL, '/receiptlist.crux?arsid=13', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.12.00.00', 'Penerimaan Klaim Ko-Asuransi', NULL, '/receiptlist3.crux?arsid=14', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.13.00.00', 'Realisasi Titipan Premi', NULL, '/receiptpembayaranrealisasititipanlist.crux?arsid=25', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.14.00.00', 'Penerimaan Premi Via Titipan', NULL, '/receipttitipanlist.crux?arsid=15', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.15.00.00', '16. Penerimaan Premi Polis Sementara', NULL, '/receiptlist.crux?arsid=16', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.16.00.00', '17. Realisasi Titipan Premi', NULL, '/receiptlist.crux?arsid=17', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.17.00.00', '10. Penerimaan Premi (Versi 2)', NULL, '/receiptlist.crux?arsid=26', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.18.00.00', '11. Pembayaran Komisi (Versi 2)', NULL, '/receiptpembayarankomisilist.crux?arsid=27', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.19.00.00', '12. Penerimaan Premi (Versi 3)', NULL, '/receiptlist.crux?arsid=28', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.20.00.00', 'Penerimaan Inward Facultative', NULL, '/receiptpembayaranreaslist.crux?arsid=29', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.21.00.00', 'Penerimaan Inward Treaty', NULL, '/receiptpembayaranreaslist.crux?arsid=30', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.22.00.00', 'Penerimaan Inward Excess Of Loss', NULL, '/receiptpembayaranreaslist.crux?arsid=31', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('35.05.10.23.00.00', 'Penerimaan Profit Comission Inward Treaty', NULL, '/receiptpembayaranreaslist.crux?arsid=32', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.16.01.00.00.00', '{L-ENG Neraca dan Laba Rugi-L}{L-INA Neraca dan Laba Rugi-L}', NULL, '/fin_report.go.crux?rpt=account', NULL, NULL, NULL);
INSERT INTO s_functions VALUES ('40.16.02.00.00.00', '{L-ENG Kas Bank-L}{L-INA Kas Bank-L}', NULL, '/fin_report.go.crux?rpt=kas', NULL, NULL, NULL);

