<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Frameset//EN""http://www.w3.org/TR/REC-html40/frameset.dtd">
<!--NewPage-->
<HTML>
<HEAD>
<!-- Generated by javadoc on Thu Jun 10 20:39:45 MDT 2004 -->
<TITLE>
Cron Expression
</TITLE>
<LINK REL ="stylesheet" TYPE="text/css" HREF="../../jd_stylesheet.css" TITLE="Style">
</HEAD>
<BODY BGCOLOR="white">
<p><font face="Arial, Helvetica, sans-serif"> For those unfamiliar with "cron",
  this means being able to create a firing schedule such as: "At 8:00am every
  Monday through Friday" or "At 1:30am every last Friday of the month". </font></p>
<p><font face="Arial, Helvetica, sans-serif"> A "Cron-Expression" is a string
  comprised of 6 or 7 fields separated by white space. The 6 mandatory and 1 optional
  fields are as follows: <br>
  </font>
<table cellspacing="8">
  <tr>
    <th align="left"><font face="Arial, Helvetica, sans-serif">Field Name</font></th>
    <th align="left">&nbsp;</th>
    <th align="left"><font face="Arial, Helvetica, sans-serif">Allowed Values</font></th>
    <th align="left">&nbsp;</th>
    <th align="left"><font face="Arial, Helvetica, sans-serif">Allowed Special
      Characters</font></th>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Seconds</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0-59</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>, - * /</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Minutes</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0-59</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>, - * /</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Hours</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0-23</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>, - * /</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Day-of-month</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>1-31</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>, - * ? /
      L C</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Month</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>1-12 or JAN-DEC</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>, - * /</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Day-of-Week</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>1-7 or SUN-SAT</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>, - * ? /
      L C #</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Year (Optional)</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>empty, 1970-2099</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>, - * /</code></font></td>
  </tr>
</table>
<p><font face="Arial, Helvetica, sans-serif"> The '*' character is used to specify
  all values. For example, "*" in the minute field means "every minute". </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The '?' character is allowed for
  the day-of-month and day-of-week fields. It is used to specify 'no specific
  value'. This is useful when you need to specify something in one of the two
  fileds, but not the other. See the examples below for clarification. </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The '-' character is used to specify
  ranges For example "10-12" in the hour field means "the hours 10, 11 and 12".
  </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The ',' character is used to specify
  additional values. For example "MON,WED,FRI" in the day-of-week field means
  "the days Monday, Wednesday, and Friday". </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The '/' character is used to specify
  increments. For example "0/15" in the seconds field means "the seconds 0, 15,
  30, and 45". And "5/15" in the seconds field means "the seconds 5, 20, 35, and
  50". You can also specify '/' after the '*' character - in this case '*' is
  equivalent to having '0' before the '/'. </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The 'L' character is allowed for
  the day-of-month and day-of-week fields. This character is short-hand for "last",
  but it has different meaning in each of the two fields. For example, the value
  "L" in the day-of-month field means "the last day of the month" - day 31 for
  January, day 28 for February on non-leap years. If used in the day-of-week field
  by itself, it simply means "7" or "SAT". But if used in the day-of-week field
  after another value, it means "the last xxx day of the month" - for example
  "6L" means "the last friday of the month". When using the 'L' option, it is
  important not to specify lists, or ranges of values, as you'll get confusing
  results. </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The 'W' character is allowed for
  the day-of-month field. This character is used to specify the weekday (Monday-Friday)
  nearest the given day. As an example, if you were to specify "15W" as the value
  for the day-of-month field, the meaning is: "the nearest weekday to the 15th
  of the month". So if the 15th is a Saturday, the trigger will fire on Friday
  the 14th. If the 15th is a Sunday, the trigger will fire on Monday the 16th.
  If the 15th is a Tuesday, then it will fire on Tuesday the 15th. However if
  you specify "1W" as the value for day-of-month, and the 1st is a Saturday, the
  trigger will fire on Monday the 3rd, as it will not 'jump' over the boundary
  of a month's days. The 'W' character can only be specified when the day-of-month
  is a single day, not a range or list of days. </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The 'L' and 'W' characters can also
  be combined for the day-of-month expression to yield 'LW', which translates
  to "last weekday of the month". </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The '#' character is allowed for
  the day-of-week field. This character is used to specify "the nth" XXX day of
  the month. For example, the value of "6#3" in the day-of-week field means the
  third Friday of the month (day 6 = Friday and "#3" = the 3rd one in the month).
  Other examples: "2#1" = the first Monday of the month and "4#5" = the fifth
  Wednesday of the month. Note that if you specify "#5" and there is not 5 of
  the given day-of-week in the month, then no firing will occur that month. </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The 'C' character is allowed for
  the day-of-month and day-of-week fields. This character is short-hand for "calendar".
  This means values are calculated against the associated calendar, if any. If
  no calendar is associated, then it is equivalent to having an all-inclusive
  calendar. A value of "5C" in the day-of-month field means "the first day included
  by the calendar on or after the 5th". A value of "1C" in the day-of-week field
  means "the first day included by the calendar on or after sunday". </font></p>
<p><font face="Arial, Helvetica, sans-serif"> The legal characters and the names
  of months and days of the week are not case sensitive. </font></p>
<p><font face="Arial, Helvetica, sans-serif"> Here are some full examples: <br>
  </font>
<table cellspacing="8">
  <tr>
    <th align="left"><font face="Arial, Helvetica, sans-serif">Expression</font></th>
    <th align="left">&nbsp;</th>
    <th align="left"><font face="Arial, Helvetica, sans-serif">Meaning</font></th>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 0 12 *
      * ?</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 12pm
      (noon) every day</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      ? * *</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      every day</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      * * ?</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      every day</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      * * ? *</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      every day</code></font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      * * ? 2005</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      every day during the year 2005</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 * 14 *
      * ?</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire every
      minute starting at 2pm and ending at 2:59pm, every day</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 0/5 14
      * * ?</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire every
      5 minutes starting at 2pm and ending at 2:55pm, every day</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 0/5 14,18
      * * ?</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire every
      5 minutes starting at 2pm and ending at 2:55pm, AND fire every 5 minutes
      starting at 6pm and ending at 6:55pm, every day</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 0-5 14
      * * ?</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire every
      minute starting at 2pm and ending at 2:05pm, every day</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 10,44
      14 ? 3 WED</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 2:10pm
      and at 2:44pm every Wednesday in the month of March.</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      ? * MON-FRI</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      every Monday, Tuesday, Wednesday, Thursday and Friday</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      15 * ?</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      on the 15th day of every month</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      L * ?</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      on the last day of every month</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      ? * 6L</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      on the last Friday of every month</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      ? * 6L</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      on the last Friday of every month</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      ? * 6L 2002-2005</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      on every last friday of every month during the years 2002, 2003, 2004 and
      2005</code> </font></td>
  </tr>
  <tr>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>0 15 10
      ? * 6#3</code></font></td>
    <td align="left"><font face="Arial, Helvetica, sans-serif">&nbsp;</font>
    <td align="left"><font face="Arial, Helvetica, sans-serif"><code>Fire at 10:15am
      on the third Friday of every month</code> </font></td>
  </tr>
</table>
<p><font face="Arial, Helvetica, sans-serif"> Pay attention to the effects of
  '?' and '*' in the day-of-week and day-of-month fields! </font></p>
<p> <font face="Arial, Helvetica, sans-serif"><b>NOTES:</b> </font>
<ul>
  <li><font face="Arial, Helvetica, sans-serif">Support for the features described
    for the 'C' character is not complete.</font></li>
  <li><font face="Arial, Helvetica, sans-serif">Support for specifying both a
    day-of-week and a day-of-month value is not complete (you'll need to use the
    '?' character in on of these fields). </font></li>
  <li><font face="Arial, Helvetica, sans-serif">Be careful when setting fire times
    between mid-night and 1:00 AM - "daylight savings" can cause a skip or a repeat
    depending on whether the time moves back or jumps forward.</font></li>
</ul>
<P>
</BODY>
</HTML>
